<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Pre_Launch_WP
 * @since 1.0.0
 */
?>

<!--Start Footer-->
<footer class="footer">


    <div class="footer-bottom">
        <div class="bot-inner">

            <!--Copyright Info-->
            <?php wp_nav_menu( array( 'theme_location' => 'footer-column-1' ) ); ?>
            <p>© <?php echo date("Y"); ?> Foothills Church</p>

        </div>
    </div>
</footer>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>

